# Server Build and Deploy （Release to blob）

name: Server-end-build-deploy
on:
  push:
    branches: ["v2", "main"]
    paths:
      - ".github/workflows/server-cd.yml"
      - "server.net/**"


permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true



env:
  AZURE_WEBAPP_NAME: Sticker
  AZURE_WEBAPP_PACKAGE_PATH: 'server.net' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use


jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          cd server.net
          dotnet build --configuration Release --no-restore
          dotnet publish -c Release -o ../dotnet-webapp -r linux-x64 --self-contained true /p:UseAppHost=true

#      - name: Test
#        run: |
#          cd DotNet.WebApp.Tests
#          dotnet test --no-restore --verbosity normal

      - uses: azure/webapps-deploy@v2
        name: Deploy
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/dotnet-webapp'
